{
 "title": "Ad-hoc Explorer",
 "description": "Explorer-like dashboard for ad-hoc PromQL queries in read-only Grafana instances",
 "tags": [
  "explorer",
  "adhoc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "metric", "label": "Metrics", "query": "label_values(__name__)" },
   { "name": "query", "label": "PromQL" },
   { "name": "step", "label": "Min Step" }
  ]
 },
 "panels": [
  {
   "title": "Time Series",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "$query", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count($query)", "legendFormat": "Series Count" },
    { "expr": "avg($query)", "legendFormat": "Avg" },
    { "expr": "sum($query)", "legendFormat": "Sum" }
   ]
  },
  {
   "title": "Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, $query)",
     "legendFormat": "{{__name__}} {{pod}} {{container}} {{namespace}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bottom 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(10, $query)",
     "legendFormat": "{{__name__}} {{pod}} {{container}} {{namespace}} {{instance}}"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "$query" }
   ]
  }
 ]
}