apiVersion: v2
appVersion: 2.10.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-210@sha256:9ea907b5b073b555724b3579dec688b82b5ea9437de484d53e6212d9e049f274
type: application
version: 2.10.2
