apiVersion: v2
appVersion: 2.10.2
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-210@sha256:6b80ae204f71a52269e361d7255b2021f4d1b9aa0e60e763a504e508c12c02a8
type: application
version: 2.10.2
